### ISSUE TITLE
PHS CSS style

### ISSUE THREAD

**Issue by Moohan** [Public-Health-Scotland/phstemplates#66]
This possibly belongs in `phsstyles` rather than here.

It would be good to have a set of CSS styles that can be added to an RMarkdown doc (I think it already exists for the Shiny app). To apply standard PHS colours, formatting etc.

I combined the Shiny version with someone else's, and have been applying this one to docs.
<details>
  <summary>style.css</summary>

```CSS
/* Setting header colour */
  h1, .h1, h2, .h2, h3, .h3, h4, .h4, h5, .h5, h6, .h6 {
    margin-top: 20px;
    margin-bottom: 10px;
    color: #3F3685;
  }

/* Body styles */
  body {
    font-family: Arial;
    font-size: 16px;
    line-height: 1.5;
    color: #000000;
    background-color: #ffffff;
  }

/* Style hyperlinks */
  .externallink {color: #3F3685; font-weight: bold;}
.externallink:hover {color: #8FBFC2;}

.tocify {
    width: 20%;
    max-height: 90%;
    overflow: auto;
    margin-left: 2%;
    position: fixed;
    border: 4px solid #3F3685;
    border-radius: 15px;
}

.tocify .tocify-item a, .tocify .list-group-item {
    padding: 4px;
}

.list-group-item.active, .list-group-item.active:focus, .list-group-item.active:hover {
    z-index: 2;
    color: #fff;
    background-color: #655E9D;
    border-color: #004785;
    text-decoration: underline;
}
```
</details>

It would be good to have a 'template', so you can create a new RMarkdown doc which has this in the YAML header.

```yaml
output: 
  html_document:
    css: style.css
    toc: true
    toc_float: true
```

It might also be useful to have an Addin that would create the `style.css` file in the current directory, to be used as needed.
